// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zslfhmjuepjdoeoczsrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzbGZobWp1ZXBqZG9lb2N6c3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDYzMzQsImV4cCI6MjA3MDY4MjMzNH0.Hh3818VD7sxgYI8DUrcm5ZGnIYMMiozx1nPPgBuK-8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});